### PR TITLE
Reuse pie-chart

### PR DESCRIPTION
**Pull request by just-boris**
_now it is donut_

Sorry, can't attach a screenshot, my internet is too slow for it.

### CODE REVIEW

**Comment by lanwen** [comment]
wow, thanks!

**Comment by lanwen** [comment]
Now it doesn't load translation after first load
image

But donut looks pretty cool

**Comment by just-boris** [comment]
should work fine now

**Comment by lanwen** [comment]
merged in b32ad26b82a3dd32505dc2faa28bbab30d03c15f

**Pull request closed without merging**
